//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothing_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int id { get; set; }
        public Nullable<int> idMain { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<int> caunt { get; set; }
    
        public virtual account account { get; set; }
        public virtual main main { get; set; }
    }
}
